### ISSUE TITLE
code

### ISSUE THREAD

**Issue by AlexNmSED** [Puzzled-Hui/AttentionBased-MIS#2]
你好，你这个还计划实现嘛？我也有这个想法，我们可以一起

**Comment by Puzzled-Hui** [comment]
你好，我会继续更新这个仓库，实际上我已在我的私人仓库中更新完毕，不过论文期刊还在审稿当中，后面会开源。

如果你有兴趣加入进来的话，可否告知一下学校姓名年级呢？

祝好

----- 原始邮件 -----
发件人: "AlexNmSED" ***@***.***>
收件人: "Puzzled-Hui/AttentionBased-MIS" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期四, 2021年 7 月 22日 下午 11:47:13
主题: [Puzzled-Hui/AttentionBased-MIS] code (#2)

你好，你这个还计划实现嘛？我也有这个想法，我们可以一起

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Puzzled-Hui/AttentionBased-MIS/issues/2

**Comment by AlexNmSED** [comment]
大连理工大学，目前博一

**Comment by Puzzled-Hui** [comment]
你好，我是上海交通大学-研一，那我近期可以创建一个项目，把你一起拉进来 你觉得如何？

----- 原始邮件 -----
发件人: "AlexNmSED" ***@***.***>
收件人: "Puzzled-Hui/AttentionBased-MIS" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期四, 2021年 7 月 22日 下午 11:47:13
主题: [Puzzled-Hui/AttentionBased-MIS] code (#2)

你好，你这个还计划实现嘛？我也有这个想法，我们可以一起

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Puzzled-Hui/AttentionBased-MIS/issues/2

**Comment by AlexNmSED** [comment]
好的，没有问题
